name: Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      # Step 4: Azure Login - 使用 Azure 登录操作
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Step 5: Deploy to Azure Web App - 使用发布配置文件部署
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: votes  # 替换为你的 Azure Web 应用名称
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # 发布配置文件
          package: .  # 指定要部署的文件夹或文件路径
