name: Build and deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ 90b9a999-6ab8-4e12-a888-ea31e1a732d4 }}
          client-secret: ${{ 4897abe9-af28-4feb-9155-ef0e0501d0ee }}
          tenant-id: ${{ 61ecf2aa-09cf-4868-bbdb-da1215cbda8f}}
          subscription-id: ${{ 9fc214ed-243a-49b5-af4f-69d0fd96ce8c }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'votes'  # 替换为您的 Azure Web 应用名称
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # 发布配置文件
          package: .
